# 工业机器人焊接应用配置文件

# 机器人配置
robot:
  name: "industrial_welding_robot"
  type: "6dof_articulated"
  manufacturer: "Leee Robotics"
  model: "IRW-1000"

  # 运动学参数 (DH参数)
  dh_parameters:
    a: [0.0, 0.5, 0.5, 0.0, 0.0, 0.0]
    alpha: [1.5708, 0.0, 0.0, 1.5708, -1.5708, 0.0]
    d: [0.2, 0.0, 0.0, 0.3, 0.0, 0.1]
    theta_offset: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  # 关节限制
  joint_limits:
    min: [-3.14159, -2.0944, -2.96706, -2.0944, -2.0944, -6.28319]
    max: [3.14159, 2.0944, 2.96706, 2.0944, 2.0944, 6.28319]

  # 工作空间
  workspace:
    min: [-1.0, -1.0, 0.0]
    max: [1.0, 1.0, 1.5]

# 焊接设备配置
welding_equipment:
  type: "MIG_welder"
  model: "Leee WeldMaster Pro"
  power_source: "inverter"
  wire_diameter: 1.2  # mm

  # 默认焊接参数
  default_parameters:
    process: "MIG"
    voltage: 24.0      # V
    current: 150.0     # A
    speed: 5.0         # mm/s
    wire_feed_rate: 6.0    # m/min
    gas_flow_rate: 12.0    # L/min

  # 安全限制
  safety_limits:
    max_voltage: 40.0
    max_current: 300.0
    max_temperature: 80.0
    max_speed: 15.0

# 传感器配置
sensors:
  voltage_sensor:
    type: "analog"
    range: [0.0, 50.0]
    accuracy: 0.1
    update_rate: 1000  # Hz

  current_sensor:
    type: "analog"
    range: [0.0, 500.0]
    accuracy: 1.0
    update_rate: 1000

  temperature_sensor:
    type: "thermocouple"
    range: [0.0, 200.0]
    accuracy: 1.0
    update_rate: 10

  arc_length_sensor:
    type: "laser"
    range: [0.0, 20.0]
    accuracy: 0.1
    update_rate: 100

# 运动控制配置
motion_control:
  controller_type: "PID"
  pid_gains:
    kp: [100.0, 100.0, 100.0, 50.0, 50.0, 20.0]
    ki: [10.0, 10.0, 10.0, 5.0, 5.0, 2.0]
    kd: [5.0, 5.0, 5.0, 2.0, 2.0, 1.0]

  trajectory:
    max_velocity: 1.0      # rad/s
    max_acceleration: 2.0  # rad/s²
    blend_radius: 0.01     # m
    time_step: 0.001       # s

# 安全配置
safety:
  emergency_stop_enabled: true
  collision_detection_enabled: true
  workspace_monitoring_enabled: true
  temperature_monitoring_enabled: true

  # 安全区域
  safe_zones:
    - name: "workpiece_area"
      min: [0.0, 0.0, 0.0]
      max: [0.5, 0.5, 0.3]
    - name: "maintenance_area"
      min: [-0.2, -0.2, 0.0]
      max: [0.2, 0.2, 0.5]

# 日志配置
logging:
  level: "INFO"
  file: "logs/welding_app.log"
  max_file_size: 10485760  # 10MB
  max_files: 5
  console_output: true

# 网络配置
network:
  interface_type: "industrial_ethernet"
  protocol: "EtherCAT"
  ip_address: "192.168.1.100"
  subnet_mask: "255.255.255.0"
  gateway: "192.168.1.1"

# 材料数据库
materials:
  mild_steel:
    density: 7850.0
    melting_point: 1450.0
    thermal_conductivity: 50.0
    recommended_parameters:
      voltage: 24.0
      current: 150.0
      speed: 5.0

  stainless_steel:
    density: 8000.0
    melting_point: 1400.0
    thermal_conductivity: 16.0
    recommended_parameters:
      voltage: 26.0
      current: 140.0
      speed: 4.0

  aluminum:
    density: 2700.0
    melting_point: 660.0
    thermal_conductivity: 237.0
    recommended_parameters:
      voltage: 22.0
      current: 120.0
      speed: 6.0
